#!/bin/bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------
MIXER="default"
SCONTROL="Master"
VOLUME_TEXT="none"
# The first parameter sets the step to change the volume by (and units to display)
# This may be in in % or dB (eg. 5% or 3dB)
STEP="5%"
volume() {
  IS_MUTE=$(awk -F"[][]" '/dB/ { print $6 }' <(amixer -D $MIXER get $SCONTROL))
  VOLUME=$(awk -F"[][]" '/dB/ { print $2 }' <(amixer -D $MIXER get $SCONTROL))
  VOLUME_TEXT="  $VOLUME"
  if [ "$IS_MUTE" = "off" ]; then
    VOLUME_TEXT=" MUTE"
  fi
  echo "$VOLUME_TEXT"
#  if [ $VOLUME -lt 10% ]; then
#    VOLUME=""
#  fi
}

#------------------------------------------------------------------------

case $BLOCK_BUTTON in
  3) amixer -q -D $MIXER sset $SCONTROL toggle 
	 amixer -q -D $MIXER sset Speaker unmute 
	 amixer -q -D $MIXER sset Headphone unmute 
	;;  # right click, mute/unmute
  4) amixer -q -D $MIXER sset $SCONTROL ${STEP}+ unmute ;; # scroll up, increase
  5) amixer -q -D $MIXER sset $SCONTROL ${STEP}- unmute ;; # scroll down, decrease
esac
sleep 0.1
volume

